DROP TABLE IF EXISTS Cards CASCADE;
 DROP TABLE IF EXISTS Bills CASCADE;
 DROP TABLE IF EXISTS Users CASCADE;
 DROP TABLE IF EXISTS Replenishments CASCADE;
 DROP TABLE IF EXISTS Partners CASCADE;
 DROP TABLE IF EXISTS Operations CASCADE;
